const ActionTypes = {
  UPDATE_TITLE: "UPDATE_TITLE",
  GET_PRODUCTS: "GET_PRODUCTS",
  SET_PRODUCT_VIEW_DATA: "SET_PRODUCT_VIEW_DATA",
  UPDATE_PRODUCT_VIEW_DATA: "UPDATE_PRODUCT_VIEW_DATA",
  RESET_PRODUCT_VIEW_DATA: "RESET_PRODUCT_VIEW_DATA",
  SET_SELECTED_OPTION: "SET_SELECTED_OPTION",
  ADD_TO_CART: "ADD_TO_CART",
  UPDATE_CART_QUANTITY: "UPDATE_CART_QUANTITY",
  REMOVE_PRODUCT_OPTION_CART: "REMOVE_PRODUCT_OPTION_CART",
  REMOVE_PRODUCT_FROM_CART: "REMOVE_PRODUCT_FROM_CART",
  CALCULATE_CART: "CALCULATE_CART",
};

export default ActionTypes;
